repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.4
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi ]
      args: [ --fix ]
    - id: ruff
      args: ["check", "--select", "I", "--fix"]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: ['--profile', 'black']
